apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: broadcaster-svc
spec:
  type: ClusterIP
  selector:
    app: broadcaster
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: broadcaster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broadcaster
  strategy:
    canary:
      steps:
        - setWeight: 100
        - analysis:
            templates:
              - templateName: cpu-usage
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: BROADCASTER/IMAGE
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-webhook-url
                  key: DISCORD_WEBHOOK_URL
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: NATS_URL
          resources:
            limits:
              cpu: "100m"
              memory: "64Mi"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3001
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: project
  name: broadcaster-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: broadcaster
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
