apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: exercise
  name: ping-pong-svc
spec:
  template:
    spec:
      containers:
        - name: ping-pong
          image: PING_PONG/IMAGE
          ports:
            - containerPort: 8081
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pingpong-pg-password
                  key: PINGPONG_PG_PASSWORD
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PINGPONG_PG_USER
            - name: PG_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PINGPONG_PG_DB
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8081
