apiVersion: v1
kind: Service
metadata:
  namespace: exercise
  name: ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercise
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: ronituohino/ping-pong:2.07.28
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pingpong-pg-password
                  key: PINGPONG_PG_PASSWORD
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PINGPONG_PG_USER
            - name: PG_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PINGPONG_PG_DB
