apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: LOG_OUTPUT/IMAGE
  newName: ronituohino/log-output
  newTag: e03c9cb6d3329ff1c22aa05406842759ec9407dd
- name: PING_PONG/IMAGE
  newName: ronituohino/ping-pong
  newTag: e03c9cb6d3329ff1c22aa05406842759ec9407dd
resources:
- namespaces/namespace.yaml
- manifests/configmap.yaml
- manifests/ping-pong-postgres.yaml
- manifests/ping-pong.yaml
- manifests/log-output.yaml
- manifests/ingress.yaml
