apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-project
resources:
- namespaces/namespace.yaml
- ./../../base

images:
- name: BROADCASTER/IMAGE
  newName: ronituohino/staging-broadcaster
  newTag: b5995c25b1cfede6aae872d9036c75a43bdffa77
- name: GENERATE_TODO/IMAGE
  newName: ronituohino/staging-generate-todo
  newTag: b5995c25b1cfede6aae872d9036c75a43bdffa77
- name: PG_BACKUP/IMAGE
  newName: ronituohino/staging-pg-backup
  newTag: b5995c25b1cfede6aae872d9036c75a43bdffa77
- name: TODO_API/IMAGE
  newName: ronituohino/staging-todo-api
  newTag: b5995c25b1cfede6aae872d9036c75a43bdffa77
- name: TODO_APP/IMAGE
  newName: ronituohino/staging-todo-app
  newTag: b5995c25b1cfede6aae872d9036c75a43bdffa77
