apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-project
resources:
- namespaces/namespace.yaml
- ./../../base

images:
- name: BROADCASTER/IMAGE
  newName: ronituohino/staging-broadcaster
  newTag: 41d3c945fe47e1240d217a2f3ad12676ee00e53d
- name: GENERATE_TODO/IMAGE
  newName: ronituohino/staging-generate-todo
  newTag: 41d3c945fe47e1240d217a2f3ad12676ee00e53d
- name: PG_BACKUP/IMAGE
  newName: ronituohino/staging-pg-backup
  newTag: 41d3c945fe47e1240d217a2f3ad12676ee00e53d
- name: TODO_API/IMAGE
  newName: ronituohino/staging-todo-api
  newTag: 41d3c945fe47e1240d217a2f3ad12676ee00e53d
- name: TODO_APP/IMAGE
  newName: ronituohino/staging-todo-app
  newTag: 41d3c945fe47e1240d217a2f3ad12676ee00e53d
