apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-project
resources:
- namespaces/namespace.yaml
- volumes/pv1.yaml
- volumes/pv2.yaml
- manifests/analysistemplate.yaml
- ./../../base

patches:
- path: manifests/broadcaster.yaml
- path: manifests/todo-api-pg.yaml
- path: manifests/todo-api.yaml
- path: manifests/todo-app.yaml

images:
- name: BROADCASTER/IMAGE
  newName: ronituohino/staging-broadcaster
  newTag: 49b87490d34e9fbf0acf9f2e5c182a5e2cbc9a50
- name: GENERATE_TODO/IMAGE
  newName: ronituohino/staging-generate-todo
  newTag: 49b87490d34e9fbf0acf9f2e5c182a5e2cbc9a50
- name: PG_BACKUP/IMAGE
  newName: ronituohino/staging-pg-backup
  newTag: 49b87490d34e9fbf0acf9f2e5c182a5e2cbc9a50
- name: TODO_API/IMAGE
  newName: ronituohino/staging-todo-api
  newTag: 49b87490d34e9fbf0acf9f2e5c182a5e2cbc9a50
- name: TODO_APP/IMAGE
  newName: ronituohino/staging-todo-app
  newTag: 49b87490d34e9fbf0acf9f2e5c182a5e2cbc9a50
