apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-project
resources:
- namespaces/namespace.yaml
- volumes/pv1.yaml
- volumes/pv2.yaml
- ./../../base

patches:
- path: manifests/broadcaster.yaml
- path: manifests/todo-api-pg.yaml
- path: manifests/todo-app.yaml

images:
- name: BROADCASTER/IMAGE
  newName: ronituohino/staging-broadcaster
  newTag: c0ff5c2424e9ad270758f5bafe049d8e6168f8fd
- name: GENERATE_TODO/IMAGE
  newName: ronituohino/staging-generate-todo
  newTag: c0ff5c2424e9ad270758f5bafe049d8e6168f8fd
- name: PG_BACKUP/IMAGE
  newName: ronituohino/staging-pg-backup
  newTag: c0ff5c2424e9ad270758f5bafe049d8e6168f8fd
- name: TODO_API/IMAGE
  newName: ronituohino/staging-todo-api
  newTag: c0ff5c2424e9ad270758f5bafe049d8e6168f8fd
- name: TODO_APP/IMAGE
  newName: ronituohino/staging-todo-app
  newTag: c0ff5c2424e9ad270758f5bafe049d8e6168f8fd
