apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-project
resources:
- namespaces/namespace.yaml
- ./../../base

patches:
- path: manifests/broadcaster.yaml
- path: manifests/todo-api.yaml
- path: manifests/todo-app.yaml

namePrefix: staging-

images:
- name: BROADCASTER/IMAGE
  newName: ronituohino/staging-broadcaster
  newTag: 1820214be118d36862a7f3ec695d52dffd192f9b
- name: GENERATE_TODO/IMAGE
  newName: ronituohino/staging-generate-todo
  newTag: 1820214be118d36862a7f3ec695d52dffd192f9b
- name: PG_BACKUP/IMAGE
  newName: ronituohino/staging-pg-backup
  newTag: 1820214be118d36862a7f3ec695d52dffd192f9b
- name: TODO_API/IMAGE
  newName: ronituohino/staging-todo-api
  newTag: 1820214be118d36862a7f3ec695d52dffd192f9b
- name: TODO_APP/IMAGE
  newName: ronituohino/staging-todo-app
  newTag: 1820214be118d36862a7f3ec695d52dffd192f9b
