apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-project
resources:
- namespaces/namespace.yaml
- ./../../base

patches:
- path: manifests/broadcaster.yaml
- path: manifests/todo-api.yaml
- path: manifests/todo-app.yaml

namePrefix: staging-

images:
- name: BROADCASTER/IMAGE
  newName: ronituohino/staging-broadcaster
  newTag: 9fdfd92e77b62b435ca31e19411cfecb0d34ce05
- name: GENERATE_TODO/IMAGE
  newName: ronituohino/staging-generate-todo
  newTag: 9fdfd92e77b62b435ca31e19411cfecb0d34ce05
- name: PG_BACKUP/IMAGE
  newName: ronituohino/staging-pg-backup
  newTag: 9fdfd92e77b62b435ca31e19411cfecb0d34ce05
- name: TODO_API/IMAGE
  newName: ronituohino/staging-todo-api
  newTag: 9fdfd92e77b62b435ca31e19411cfecb0d34ce05
- name: TODO_APP/IMAGE
  newName: ronituohino/staging-todo-app
  newTag: 9fdfd92e77b62b435ca31e19411cfecb0d34ce05
