apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-project
resources:
- namespaces/namespace.yaml
- volumes/pv1.yaml
- volumes/pv2.yaml
- ./../../base

patches:
- path: manifests/broadcaster.yaml
- path: manifests/todo-api-pg.yaml
- path: manifests/todo-app.yaml

images:
- name: BROADCASTER/IMAGE
  newName: ronituohino/staging-broadcaster
  newTag: 995f0dba818184f04346ce9dccb9b9dc74e81b1f
- name: GENERATE_TODO/IMAGE
  newName: ronituohino/staging-generate-todo
  newTag: 995f0dba818184f04346ce9dccb9b9dc74e81b1f
- name: PG_BACKUP/IMAGE
  newName: ronituohino/staging-pg-backup
  newTag: 995f0dba818184f04346ce9dccb9b9dc74e81b1f
- name: TODO_API/IMAGE
  newName: ronituohino/staging-todo-api
  newTag: 995f0dba818184f04346ce9dccb9b9dc74e81b1f
- name: TODO_APP/IMAGE
  newName: ronituohino/staging-todo-app
  newTag: 995f0dba818184f04346ce9dccb9b9dc74e81b1f
