apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-project
resources:
  - namespaces/namespace.yaml
  - ./../../base

patches:
  - path: manifests/broadcaster.yaml

namePrefix: staging-

images:
  - name: BROADCASTER/IMAGE
    newName: ronituohino/staging-broadcaster
    newTag: f3c84f7000213456379138843f9cf73b147eb579
  - name: GENERATE_TODO/IMAGE
    newName: ronituohino/staging-generate-todo
    newTag: f3c84f7000213456379138843f9cf73b147eb579
  - name: PG_BACKUP/IMAGE
    newName: ronituohino/staging-pg-backup
    newTag: f3c84f7000213456379138843f9cf73b147eb579
  - name: TODO_API/IMAGE
    newName: ronituohino/staging-todo-api
    newTag: f3c84f7000213456379138843f9cf73b147eb579
  - name: TODO_APP/IMAGE
    newName: ronituohino/staging-todo-app
    newTag: f3c84f7000213456379138843f9cf73b147eb579
