apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-project
resources:
- namespaces/namespace.yaml
- ./../../base

patches:
- path: manifests/broadcaster.yaml
- path: manifests/hpa.yaml

namePrefix: staging-

images:
- name: BROADCASTER/IMAGE
  newName: ronituohino/staging-broadcaster
  newTag: 06dad987227315331d06548e03287cf1b286db07
- name: GENERATE_TODO/IMAGE
  newName: ronituohino/staging-generate-todo
  newTag: 06dad987227315331d06548e03287cf1b286db07
- name: PG_BACKUP/IMAGE
  newName: ronituohino/staging-pg-backup
  newTag: 06dad987227315331d06548e03287cf1b286db07
- name: TODO_API/IMAGE
  newName: ronituohino/staging-todo-api
  newTag: 06dad987227315331d06548e03287cf1b286db07
- name: TODO_APP/IMAGE
  newName: ronituohino/staging-todo-app
  newTag: 06dad987227315331d06548e03287cf1b286db07
