apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picture-cache-claim # name of ther volume claim, this will be used in the deployment
spec:
  storageClassName: scn-example-pv # this is the name of the persisten volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi