apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-project
resources:
- namespaces/namespace.yaml
- volumes/pv1.yaml
- volumes/pv2.yaml
- manifests/analysistemplate.yaml
- ./../../base
- cron/daily-pg-backup.yaml

patches:
- path: manifests/broadcaster.yaml
- path: manifests/todo-api-pg.yaml
- path: manifests/todo-api.yaml
- path: manifests/todo-app.yaml

images:
- name: BROADCASTER/IMAGE
  newName: ronituohino/prod-broadcaster
  newTag: f9afdb7d13af55a3af54843bab87dcae5ff69e9c
- name: GENERATE_TODO/IMAGE
  newName: ronituohino/prod-generate-todo
  newTag: f9afdb7d13af55a3af54843bab87dcae5ff69e9c
- name: PG_BACKUP/IMAGE
  newName: ronituohino/prod-pg-backup
  newTag: f9afdb7d13af55a3af54843bab87dcae5ff69e9c
- name: TODO_API/IMAGE
  newName: ronituohino/prod-todo-api
  newTag: f9afdb7d13af55a3af54843bab87dcae5ff69e9c
- name: TODO_APP/IMAGE
  newName: ronituohino/prod-todo-app
  newTag: f9afdb7d13af55a3af54843bab87dcae5ff69e9c
