apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: broadcaster
spec:
  strategy:
    canary:
      steps:
        - setWeight: 100
        - analysis:
            templates:
              - templateName: cpu-usage
  template:
    spec:
      containers:
        - name: broadcaster
          image: BROADCASTER/IMAGE
          env:
            - name: NOTIFICATIONS_DISABLED
              value: "1"
