spec:
  template:
    spec:
      containers:
        - name: broadcaster
          image: BROADCASTER/IMAGE
          env:
            - name: NOTIFICATIONS_DISABLED
              value: 1
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: NATS_URL
          resources:
            limits:
              cpu: "50m"
              memory: "64Mi"
