apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: postgres-stset
spec:
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:17.0-alpine3.20
          ports:
            - name: web
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: staging-todo-api-pg-password
                  key: TODO_API_PG_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: staging-configmap
                  key: TODO_API_PG_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: staging-configmap
                  key: TODO_API_PG_DB
            - name: POSTGRES_HOST_AUTH_METHOD
              valueFrom:
                configMapKeyRef:
                  name: staging-configmap
                  key: TODO_API_PG_HOST_AUTH_METHOD
