apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-api-svc
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-api
  labels: { app: todo-api }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: TODO_API/IMAGE
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-api-pg-password
                  key: TODO_API_PG_PASSWORD
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: TODO_API_PG_USER
            - name: PG_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: TODO_API_PG_DB
          resources:
            limits:
              cpu: "150m"
              memory: "128Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: project
  name: todo-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-api
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
