apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
  namespace: project
spec:
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: broadcaster
    spec:
      containers:
        - env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  key: DISCORD_WEBHOOK_URL
                  name: discord-webhook-url
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  key: NATS_URL
                  name: configmap
          image: BROADCASTER/IMAGE
          name: broadcaster
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: project
  name: broadcaster-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: broadcaster
  minReplicas: 6
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
