apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: broadcaster
spec:
  strategy:
    canary:
      steps:
        - setWeight: 100
        - analysis:
            templates:
              - templateName: prod-cpu-usage
  template:
    spec:
      containers:
        - name: broadcaster
          image: BROADCASTER/IMAGE
          env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: prod-discord-webhook-url
                  key: DISCORD_WEBHOOK_URL
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: prod-configmap
                  key: NATS_URL
          resources:
            limits:
              cpu: "50m"
              memory: "64Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: project
  name: broadcaster-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: prod-broadcaster
