apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: broadcaster
spec:
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: prod-cpu-usage
