apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: postgres-stset
spec:
  template:
    spec:
      volumes:
        - name: pg-pvc-vol
          persistentVolumeClaim:
            claimName: prod-pg-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: prod-pg-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: prod-scn-pv-2
