apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: todo-app
spec:
  strategy:
    canary:
      steps:
        - setWeight: 100
        - analysis:
            templates:
              - templateName: prod-cpu-usage
  template:
    spec:
      volumes:
        - name: picture-cache
          persistentVolumeClaim:
            claimName: prod-picture-cache-claim
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: project
  name: todo-app-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: prod-todo-app
