apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: todo-api-pg-password
data:
    TODO_API_PG_PASSWORD: ENC[AES256_GCM,data:g6wjAEfp/YqJ0STrSzjizlSWMi/8Cv+LrzkQLKhF2JhbzoodgSNmfS46jUw=,iv:F6E8oXTIN2YNJf9PVhkjcteNej30GPNeKZXRQ+yZ24M=,tag:IAA2ts1MBvCEtzbH7sFUtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n9w8tgwlf6zq6q7lna3q3yw6yhfr8ekuc9aw3zap3rn0f02sq5ls6kjs7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc2dCTU04WlNOK2xrMXY0
            bTFIcm5sM1h0ODF3bjhPYzNnVDRnNDFIQXc4CnpMZGhLL0piTEtFaVhhT01kVlA5
            V2U3d2JnVFNrVmVnMU5qTytkeE42L2MKLS0tIDZObnIyNm11eWxXSWhhVXJqT2R4
            MVJqUEVIazlnTG8xRHNBNUJpam53bzAKLyh1F26927DO8ZiXEYlDxP6680aG5tqv
            RMpLz4qJJMYkPbND0+6T6Fk88gtHmmVlbtDoDO/dJ4anqLmYtPR3GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T10:02:14Z"
    mac: ENC[AES256_GCM,data:qytEfsvw3NZxC3kUfvCSVR19yDJTamSkZfBjEdMpN0cT9qI1XMaHi3Rp/Rl7HhfQecJv45ea4Oehm7d/+DEOi4x4XsA1bhCoz1C5HmdUD8Wijc1uDQTuFvfB6+VkE4p+sEIFpDhNXUIplJFPnPx21MIjrZGdX/fSNbfyWkFgYlA=,iv:KF+gdqcIqRXepra83QJAcjhjsN/W/fhvUF1dL/V6n30=,tag:3ao1myj4Kw4Y50xDh9304A==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
