apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: picture-cache
          persistentVolumeClaim:
            claimName: picture-cache-claim
      containers:
        - name: todo-app
          image: ronituohino/todo-app:2.08.0
          volumeMounts:
            - name: picture-cache
              mountPath: /usr/src/app/cache
