apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: daily-pg-backup
spec:
  schedule: "45 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: my-service-account
          containers:
            - name: daily-pg-backup
              image: PG_BACKUP/IMAGE
              imagePullPolicy: IfNotPresent
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: todo-api-pg-password
                      key: TODO_API_PG_PASSWORD
                - name: PGUSER
                  valueFrom:
                    configMapKeyRef:
                      name: configmap
                      key: TODO_API_PG_USER
                - name: PGDATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: configmap
                      key: TODO_API_PG_DB
          restartPolicy: OnFailure
