apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-api-svc
spec:
  type: ClusterIP
  selector:
    app: todo-api
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3001
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: todo-api
  labels: { app: todo-api }
spec:
  selector:
    matchLabels:
      app: todo-api
  strategy:
    canary:
      steps:
        - setWeight: 100
        - analysis:
            templates:
              - templateName: cpu-usage
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: TODO_API/IMAGE
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-api-pg-password
                  key: TODO_API_PG_PASSWORD
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: TODO_API_PG_USER
            - name: PG_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: TODO_API_PG_DB
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: NATS_URL
          resources:
            limits:
              cpu: "75m"
              memory: "64Mi"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3001
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: project
  name: todo-api-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: todo-api
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
