apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: cpu-usage
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: picture-cache
          persistentVolumeClaim:
            claimName: picture-cache-claim
      containers:
        - name: todo-app
          image: TODO_APP/IMAGE
          volumeMounts:
            - name: picture-cache
              mountPath: /usr/src/app/cache
          resources:
            limits:
              cpu: "150m"
              memory: "128Mi"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: project
  name: todo-app-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: todo-app
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
