apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: project
  name: staging-pv-2
spec:
  storageClassName: staging-scn-pv-2
  capacity:
    storage: 150Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
