apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ronituohino/devops-with-kubernetes
    path: part4/4.08/kube/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
