apiVersion: v1
kind: Service
metadata:
  namespace: exercise
  name: ping-pong-svc
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercise
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: PING_PONG/IMAGE
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pingpong-pg-password
                  key: PINGPONG_PG_PASSWORD
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PINGPONG_PG_USER
            - name: PG_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PINGPONG_PG_DB
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3001
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: exercise
  name: ping-pong-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-pong
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
