name: Build and publish application

on:
  push:
    branches: main

env:
  PROJECT_ROOT: ./part4/4.08/kube
  # Services
  TODO_API_PATH: ../services/todo-api
  TODO_APP_PATH: ../services/todo-app
  BROADCASTER_PATH: ../services/broadcaster
  # Jobs
  GENERATE_TODO_PATH: ../jobs/generate-todo
  PG_BACKUP_PATH: ../jobs/pg-backup

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    env:
      ENVI: staging
    defaults:
      run:
        working-directory: ${{ env.PROJECT_ROOT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variable
        run: echo "ENVI=prod" >> $GITHUB_ENV
        if: ${{ contains(github.event.head_commit.message, '#release') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |-
          docker build -t "ronituohino/$ENVI-todo-api:$GITHUB_SHA" "$TODO_API_PATH"
          docker build -t "ronituohino/$ENVI-todo-app:$GITHUB_SHA" "$TODO_APP_PATH"
          docker build -t "ronituohino/$ENVI-broadcaster:$GITHUB_SHA" "$BROADCASTER_PATH"
          docker build -t "ronituohino/$ENVI-generate-todo:$GITHUB_SHA" "$GENERATE_TODO_PATH"
          docker build -t "ronituohino/$ENVI-pg-backup:$GITHUB_SHA" "$PG_BACKUP_PATH"

      - name: Push images
        run: |-
          docker push "ronituohino/$ENVI-todo-api:$GITHUB_SHA"
          docker push "ronituohino/$ENVI-todo-app:$GITHUB_SHA"
          docker push "ronituohino/$ENVI-broadcaster:$GITHUB_SHA"
          docker push "ronituohino/$ENVI-generate-todo:$GITHUB_SHA"
          docker push "ronituohino/$ENVI-pg-backup:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |-
          cd overlays/$ENVI
          kustomize edit set image TODO_API/IMAGE=ronituohino/$ENVI-todo-api:$GITHUB_SHA
          kustomize edit set image TODO_APP/IMAGE=ronituohino/$ENVI-todo-app:$GITHUB_SHA
          kustomize edit set image BROADCASTER/IMAGE=ronituohino/$ENVI-broadcaster:$GITHUB_SHA
          kustomize edit set image GENERATE_TODO/IMAGE=ronituohino/$ENVI-generate-todo:$GITHUB_SHA
          kustomize edit set image PG_BACKUP/IMAGE=ronituohino/$ENVI-pg-backup:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add:
            "${{ env.PROJECT_ROOT }}/overlays/${{ env.ENVI }}/kustomization.yaml"
          message: New ${{ env.ENVI }} version released ${{ github.sha }}
